### ISSUE TITLE
性能损耗

### ISSUE THREAD

**Issue by bdjimmy** [crossoverJie/distributed-redis-tool#11]
每次请求都要跟redis进行交互， redis集群故障可能会引起，整体服务不可用吧， 是否可以考虑本地延迟上报+根据机器数量集中调整配额呢

**Comment by crossoverJie** [comment]
@bdjimmy 

- 既然是分布式工具那肯定是多台应用，如果是存在本地是没法做到全局加锁、限流的作用。
- Redis 连接是通过连接池控制的，所以肯定有个最大值。
- 如果担心 Redis 故障引起不可用，那么这种非业务性质的操作可以拿一台单独的 Redis 使用，与业务隔离。
- 根据我本地的压测，支持个几千并发肯定不成问题。
- Redis 本身性能很好，一般不会出现连接导致故障。
