### ISSUE TITLE
spring2.0.5不兼容

### ISSUE THREAD

**Issue by lineagezd** [crossoverJie/distributed-redis-tool#13]
### 你使用的是哪个版本
spring2.0.5 distributed-redis-tool1.0.4
### 实际结果
Description:

Field jedisConnectionFactory in com.ppdai.demo.config.RedisLockConfig required a bean of type 'org.springframework.data.redis.connection.jedis.JedisConnectionFactory' that could not be found.
	- Bean method 'redisConnectionFactory' in 'JedisConnectionConfiguration' not loaded because @ConditionalOnMissingBean (types: org.springframework.data.redis.connection.RedisConnectionFactory; SearchStrategy: all) found beans of type 'org.springframework.data.redis.connection.RedisConnectionFactory' redisConnectionFactory

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.data.redis.connection.jedis.JedisConnectionFactory' in your configuration.

**Comment by crossoverJie** [comment]
@lineagezd 不好意思，目前只支持 `Spring4.x+` 版本。
