### ISSUE TITLE
关于Builder的入参问题

### ISSUE THREAD

**Issue by ilaotan** [crossoverJie/distributed-redis-tool#19]
可否改为接口类 RedisConnectionFactory ~~这样我觉得springboot2下也能用了~~

编辑掉...刚才试了, lettuce的用法还是有区别的,看来无法跟springboot2各种兼容升级了,只能排除lettuce,还使用jedis

不过我感觉下面这个获取姿势可以用在Builder的构造方法上.
>  if (redisConnectionFactory instanceof JedisConnectionFactory) {
>                 final JedisConnectionFactory bean1 = (JedisConnectionFactory) redisConnectionFactory;
>                 if (bean1.isRedisClusterAware()) {
>                     this.type = RedisToolsConstant.CLUSTER;
>                 }
>                 else {
>                     this.type = RedisToolsConstant.SINGLE;
>                 }
>             }

**Comment by crossoverJie** [comment]
有好的想法或者是建议可以提个 PR。

**Comment by ilaotan** [comment]
我错了调试时用的spring-data-redis 2.x ...isRedisClusterAware()方法是新加的. 在1.x里没有. 哎关了吧
