### ISSUE TITLE
lua脚本问题疑问以及优化

### ISSUE THREAD

**Issue by renzhuang** [crossoverJie/distributed-redis-tool#6]
1.lua脚本中的超时时间为什么没有设置为1s
2.是否能优化:基于注解的方式可以增加一个限流次数的值，利用反射获取到方法名后就可以实现基于方法级别的限流。

**Comment by 1156721874** [comment]
redis.call("EXPIRE", key, 2)   这个地方失效时间设置为2s的原因是什么？

**Comment by crossoverJie** [comment]
@1156721874 其实并没有什么特别的原因，1 也是可以的。
