### ISSUE TITLE
lua的意思是啊啥？

### ISSUE THREAD

**Issue by lexang** [crossoverJie/distributed-redis-tool#7]
请问 超时时间是不是设置生成1就可以了 2没什么用处吧？

**Comment by crossoverJie** [comment]
@lexang 

1. 1 秒有没有问题，只是希望这个 key 存在的时间长一些，因为在老版本的 Redis 中，过期时间有可能会多延迟一秒。
2. 一秒钟执行多少个请求是自定义的，比如这样：
https://github.com/crossoverJie/distributed-redis-tool/blob/e1b792f14d55be09ebb8abf04b5ee7f1ad6f68d7/src/test/java/com/crossoverjie/distributed/limit/RedisLimitTest.java#L75-L77

这样就只允许并发 **5** 个请求。
