### ISSUE TITLE
springboot简单整合文档或者demo 有吗，刚开始玩springboot 看不懂

### ISSUE THREAD

**Issue by 2bcheng** [crossoverJie/distributed-redis-tool#8]

**Comment by crossoverJie** [comment]
@2bcheng 

这个项目里有使用，SpringBoot 也是类似的，只需要配置这个 Bean 即可。

https://github.com/crossoverJie/SSM/blob/614652d78de66fce5ddf8092bc9e7e7b919a4714/SSM-SECONDS-KILL/SSM-SECONDS-KILL-WEB/src/main/java/com/crossoverJie/seconds/kill/config/RedisLimitConfig.java#L26-L46

或者按照 README 操作也是可以的。

https://github.com/crossoverJie/distributed-redis-tool#controllerlimit

**Comment by 2bcheng** [comment]
我研究下，谢谢

**Comment by crossoverJie** [comment]
@2bcheng 

好的 有问题再沟通。
